version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgnet
  db-slave-1:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
    ports:
      - "5433:5432"
    volumes:
      - /Users/rutkin/Develop/Otus/social/volumes/db-slave:/var/lib/postgresql/data
    networks:
      - pgnet
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  db-slave-2:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
    ports:
      - "5434:5432"
    volumes:
      - /Users/rutkin/Develop/Otus/social/volumes/db-slave-2:/var/lib/postgresql/data
    networks:
      - pgnet
    depends_on:
      - db

  haproxy:
    image: haproxy:latest
    ports:
      - "5435:5433"  # Write port
      - "5436:5434"  # Read port
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - db
      - db-slave-1
      - db-slave-2
    networks:
      - pgnet

  app:
    build: .
    depends_on:
      - haproxy
    ports:
      - "8080:8080"
    environment:
      DB_WRITE_HOST: haproxy
      DB_WRITE_PORT: 5433
      DB_READ_HOST: haproxy
      DB_READ_PORT: 5434
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: social
    networks:
      - pgnet

volumes:
  pgdata:

networks:
  pgnet:
    external: true