version: '3.8'

services:
  jmeter:
    build:
      context: ./load-tests
      dockerfile: Dockerfile.jmeter
    volumes:
      - ./load-tests/results:/results
    depends_on:
      - app
    platform: linux/amd64
    networks:
      - pgnet

networks:
  pgnet:
    external: true