version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgnet
  db-slave-1:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: social
    ports:
      - "5433:5432"
    volumes:
      - /Users/rutkin/Develop/Otus/social/volumes/db-slave:/var/lib/postgresql/data
    networks:
      - pgnet
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  db-slave-2:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: social
    ports:
      - "5434:5432"
    volumes:
      - /Users/rutkin/Develop/Otus/social/volumes/db-slave-2:/var/lib/postgresql/data
    networks:
      - pgnet
    depends_on:
      - db

  haproxy:
    image: haproxy:latest
    ports:
      - "5435:5433"  # Write port
      - "5436:5434"  # Read port
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - db
      - db-slave-1
      - db-slave-2
    networks:
      - pgnet

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - pgnet

  app:
    build: .
    depends_on:
      - haproxy
      - citus-coordinator
    ports:
      - "8080:8080"
    environment:
      DB_WRITE_HOST: haproxy
      DB_WRITE_PORT: 5433
      DB_READ_HOST: haproxy
      DB_READ_PORT: 5434
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: social
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    networks:
      - pgnet
      - citusnet

  citus-coordinator:
    image: citusdata/citus:latest
    container_name: citus-coordinator
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
      CITUS_NODE_CONNINFO: "host=citus-coordinator dbname=social user=postgres password=postgres"
    ports:
      - "5437:5432" # Dedicated port for Citus coordinator
    networks:
      - citusnet
    depends_on:
      - citus-worker
      - citus-worker-2
    volumes:
      - ./coordinator-entrypoint.sh:/docker-entrypoint-initdb.d/00-pgpass.sh:ro
    command: ["docker-entrypoint.sh", "postgres", "-c", "listen_addresses=*", "-c", "shared_preload_libraries=citus", "-c", "wal_level=logical"]
        
  citus-worker:
    image: citusdata/citus:latest
    container_name: citus-worker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
    ports:
      - "5438:5432"
    networks:
      - citusnet
    command: ["docker-entrypoint.sh", "postgres", "-c", "listen_addresses=*", "-c", "shared_preload_libraries=citus"]

  citus-worker-2:
    image: citusdata/citus:latest
    container_name: citus-worker-2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
    ports:
      - "5439:5432"
    networks:
      - citusnet
    command: ["docker-entrypoint.sh", "postgres", "-c", "listen_addresses=*", "-c", "shared_preload_libraries=citus"]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - pgnet

volumes:
  pgdata:
  db-data:

networks:
  pgnet:
    external: true
  citusnet:
    driver: bridge