FROM justb4/jmeter:latest

# Copy test files
COPY load_test.jmx /load-tests/

# Copy required CSV file
COPY data/user_ids.csv /load-tests/
COPY data/dialog_pairs.csv /load-tests/dialog_pairs.csv

# Set working directory
WORKDIR /load-tests

# Run tests
CMD ["-n", "-t", "load_test.jmx", "-l", "/results/results.jtl", "-e", "-o", "/results/report", "-j", "/results/jmeter.log"]